In [7]:
import numpy as np



In [8]:
## create a 1 dimensional array
my1dArray = np.array([1,2,3,])
print(my1dArray)


[1 2 3]


In [9]:
## 2 dimensional array
my2dArray = np.array([[1,2,3],[4,5,6]])
print(my2dArray)

[[1 2 3]
 [4 5 6]]


In [11]:
## creating an aray specifying the data type
my2dArrayFloat= np.array([[1,2,3],[4,5,6]], dtype='float')
print(my2dArrayFloat)

[[1. 2. 3.]
 [4. 5. 6.]]


In [15]:
## confirming a data type
my2dArrayFloat.dtype

dtype('float64')

In [6]:
pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/17/c1/c31d3637f2641e25c7a19adf2ae822fdaf4ddd198b05d79a92a9ce7cb63e/numpy-2.2.1-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.8 kB 330.3 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/60.8 kB 393.8 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 404.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.6 MB 2.2 MB/s eta 0:00:06
    --------------------------------------- 0.3/12.6 MB 3.5 MB/s eta 0:00:04
   - -------------------------------------- 0.6/12.6 MB 4.9 MB/s eta 0:00:03
   -- ------------------------------------- 0.8/12.6 MB 4.5 MB/s eta 0:00:03
   --- ------------------------------------ 1.2/12.6 MB 5.7 MB/s eta 0:00:03
   ---- ---------------------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [17]:
## creating a 2d array with data type in another form 
my2dArrayFloat32 = np.array([[1,2,3],[4,5,6]], dtype=np.float16)
print(my2dArrayFloat32)

[[1. 2. 3.]
 [4. 5. 6.]]


In [18]:
## confirming a data type
my2dArrayFloat32.dtype

dtype('float16')

In [25]:
## creating an array with multiple data type 
charArray1 = np.array([(1,'aaaaa',3),(4,5,'zzzzzz')], dtype='U6')
print(charArray1)

[['1' 'aaaaa' '3']
 ['4' '5' 'zzzzzz']]


In [ ]:
## numpy initialisation

In [32]:
## create an array 
## indicate the data type to the array
## and print the array and print the dtype

mynewArray = np.array([(3, 'yyyy', 7),(27, 'lllllllll', 32)], dtype='U21')
print(mynewArray)

[['3' 'yyyy' '7']
 ['27' 'lllllllll' '32']]


In [33]:
## numpy initialisation
number_rows = 2
number_columns = 3

## creating arrays specifying the data type
array0s = np.zeros((number_rows, number_columns)), dtype=np.int16
print(array0s)

[[0. 0. 0.]
 [0. 0. 0.]]


In [47]:
## create an array of ones
number_rows = 2
number_columns = 3
array1s = np.ones((number_rows, number_columns), dtype=np.int16)
print(array1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [42]:
## create an array of 50
array50s = 50 * np.ones((number_rows, number_columns), dtype='float32')
print(array50s)

[[50. 50. 50.]
 [50. 50. 50.]]


In [46]:
array7s =np.full((number_rows, number_columns), 7)
print(array7s)

[[7 7 7]
 [7 7 7]]


In [20]:
charArray1.dtype

dtype('<U21')

In [61]:
## create an array of evenly spaced values
start = 10
end = 26
step = 3

evenlyStep = np.arange(start, end, step)
print(evenlyStep)

[10 13 16 19 22 25]


In [62]:
## create an array with line space
number_samples = 5
evenlySample = np.linspace(start, end, number_samples, dtype='int')
print(evenlySample)


[10 14 18 22 26]


In [64]:
## create an identity matrix
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [67]:
## generate numbers between 0.0 and 1.0

random01 = np.random.random((2,3))
print(random01)

[[0.64450762 0.20735519 0.01041911]
 [0.01031066 0.74050939 0.05054346]]


In [81]:
## 
randoNum = np.random.randint(0, 11, (2,3))
print(randoNum)

[[ 1  4  1]
 [ 2  0 10]]


In [86]:
randomFloat = np.random.uniform(10.5,25.5, (2,3))
print(randomFloat)

[[20.21442486 10.75738027 22.04351313]
 [22.83407889 23.86281334 13.50140995]]


In [88]:
minval = 10.5
maxval =25.5
randomFloat = np.random.uniform(minval, maxval, (2,3))
print(randomFloat)

[[22.24012306 20.48405069 23.08422586]
 [13.86571429 10.75259799 24.24784085]]


In [89]:
## array inspection, indexing and slicing
a = np.array([[4,6,7], [7,9,11]] )

## find the dimensions of the array
print("a has dimensions:", a.ndim)
print("a has shape:", a.shape)
print("a has size:", a.size)
print("a has data type:", a.dtype)


a has dimensions: 2
a has shape: (2, 3)
a has size: 6
a has data type: int64


In [90]:
print(a)


[[ 4  6  7]
 [ 7  9 11]]


In [95]:
## inspecting the array
a[1,0:3]

array([ 7,  9, 11])

In [96]:
a[0:2,1]

array([6, 9])

In [98]:
a[a>3]

array([ 4,  6,  7,  7,  9, 11])

In [99]:
##diagonal of array
b= np.array([[5,6,7],[1,4,5],[2,2,2]])
print(b)

[[5 6 7]
 [1 4 5]
 [2 2 2]]


In [100]:
np.diag(b)

array([5, 4, 2])

In [108]:
## Find odd numbers and replace with their negative numbers

task_array=[0,2,4,5,3,7,8,9,5,1]

arr=np.array([0,2,4,5,3,7,8,9,5,1])
print(arr)

## find the odd numbers
odd_numbers = arr%2==1

## replace the odd numbers with their negative numbers
arr[odd_numbers] = -1 * arr[odd_numbers]
print(arr)

[0 2 4 5 3 7 8 9 5 1]
[ 0  2  4 -5 -3 -7  8 -9 -5 -1]


In [109]:
## generate a numpy array  
arr = np.array([0,2,4,5,3,7,8,9,5,1])

## find the odd number and replace them with their negative numbers, but for numbers below 7
arr[(arr%2==1) & (arr<7)] = -1 * arr[(arr%2==1) & (arr<7)]

# print the output when they are below 7
print(arr[arr<7])

##

[ 0  2  4 -5 -3 -5 -1]
